USE University

DROP TRIGGER DELETE_Students
DROP TRIGGER DELETE_Subjects
DROP TRIGGER DELETE_Faculty

GO
CREATE TRIGGER DELETE_Faculty
   ON Faculties
   INSTEAD OF DELETE
AS 
BEGIN
 SET NOCOUNT ON;
 DELETE FROM Subjects WHERE FacID IN (SELECT ID FROM DELETED)
 DELETE FROM Students WHERE FacID IN (SELECT ID FROM DELETED)
 DELETE FROM Faculties WHERE ID IN (SELECT ID FROM DELETED)
END
GO
CREATE TRIGGER DELETE_Subjects
   ON Subjects
   INSTEAD OF DELETE
AS 
BEGIN
 SET NOCOUNT ON;
 DELETE FROM Students_Subjects WHERE SubjID IN (SELECT ID FROM DELETED)
 DELETE FROM Subjects WHERE ID IN (SELECT ID FROM DELETED)
END
GO
CREATE TRIGGER DELETE_Students
   ON Students
   INSTEAD OF DELETE
AS 
BEGIN
 SET NOCOUNT ON;
 DELETE FROM Students_Subjects WHERE StudID IN (SELECT ID FROM DELETED)
 DELETE FROM Students WHERE ID IN (SELECT ID FROM DELETED)
END
GO